### ISSUE TITLE
US Zipcode list is out of date

### ISSUE THREAD

**Issue by eengoron** [closeio/tz-trout#12]
- [ ] `regenerate_data.py` script should download `http://download.geonames.org/export/zip/US.zip` and convert it to a new json file in tztrout/data.
  - Keep JSON output consistent and diff-friendly (use [this](https://github.com/closeio/tz-trout/blob/cf0a985c1eb47fad836e53514d842de57ed1c513/tztrout/data.py#L334))
  - Only keep zip code, city name, 2-letter state code and coordinates to keep the size down.
  - This should be the first step since other files depend on this data.
  - [ ] Commit the data file into repo.
  - [ ] Provide attribution in the readme: `ZIP code data is provided by www.geonames.org under under Creative Commons Attribution 3.0 License`
- [ ] Load the data in memory in place of existing `pyzipcode` data. Make sure to deduplicate city name and state code strings.
  - [ ] Get rid of `pyzipcode` dependency (`setup.py` + `requirements.txt`)
- [x] Since old database had timezones and we don't have it from geonames, use https://github.com/MrMinimal64/timezonefinder to look up timezones by zipcode's coordinates.
- [ ] Measure memory usage and tz lookup time before and after changes.
- [ ] Turn these into test cases:
  - [ ] `print tztrout.tz_ids_for_address('US', state='NY', zipcode="10065")` should return `America/New_York` but it returns None. This zipcode was introduced in 2006/7.
  - [ ] `print tztrout.tz_ids_for_address('US', state='IL', zipcode="60642")` should return `America/Chicago` but it returns None. This zipcode was introduced in 2008. 
  - [ ] `print tztrout.tz_ids_for_address('US', state='DC', zipcode="20022")` should return `America/New_York` but it returns None. There's no data on when this zip was introduced at the end of 2004. 

We're not going to use `pyzipcode3` since @tsx has concerns about maintenance of this library. It only had one database upgrade 2 years ago and no transparent process for future upgrades.

**Comment by philfreo** [comment]
@wojcikstefan Can you add some docs for what steps are needed to update the various data sources to cut a new release?

**Comment by eengoron** [comment]
Note: This also happens with Washington State Zipcode "98391. It was added in 2006/7.

`tztrout.tz_ids_for_address('US', state="WA", zipcode="98391")`

**Comment by thomasst** [comment]
@wojcikstefan Yes, please. There are no docs on how these files are generated, especially US_ZIPS_TO_TZ_IDS_MAP_PATH

**Comment by philfreo** [comment]
Is that covered in this PR already? https://github.com/closeio/tz-trout/pull/14

**Comment by eengoron** [comment]
Just for future reference, here's a list of all valid Zipcodes that return a null value for timezone:

`01434, 02228, 02298, 02340, 02455, 03285, 03586, 03593, 03823, 03861, 05408, 06042, 06338, 06461, 06495, 06792, 06828, 06838, 07395, 07699, 10065, 10075, 10949, 13235, 15289, 15295, 17202, 17408, 17611, 17622, 18302, 19060, 19176, 19190, 19195, 19388, 19415, 19906, 20022, 20023, 20027, 20189, 20237, 20355, 20376, 20509, 20511, 20528, 20529, 20588, 20598, 20792, 20810, 20811, 20883, 20993, 21065, 21409, 22025, 22107, 22108, 22551, 22556, 22803, 23114, 23295, 24205, 25403, 25404, 25405, 27497, 27527, 27528, 27815, 28035, 28263, 28271, 28312, 28759, 29021, 29395, 29707, 30049, 30112, 30156, 30160, 30169, 30270, 30536, 31026, 31059, 31136, 31562, 32003, 32006, 32026, 32143, 32163, 32318, 32723, 32753, 32885, 32896, 33112, 33222, 33336, 33449, 33472, 33473, 33508, 33545, 33575, 33579, 33596, 33646, 33812, 33900, 33929, 33966, 33967, 33973, 33974, 33976, 34212, 34269, 34290, 34291, 34637, 34638, 34692, 34714, 34715, 36210, 36421, 37544, 37934, 39813, 39815, 39817, 39818, 39823, 39824, 39825, 39826, 39827, 39828, 39829, 39832, 39834, 39836, 39837, 39840, 39841, 39842, 39845, 39846, 39851, 39852, 39854, 39859, 39861, 39862, 39866, 39867, 39870, 39877, 39885, 39886, 39897, 40129, 40598, 43069, 43194, 43195, 45280, 45400, 46037, 46062, 46085, 46262, 46296, 48033, 48193, 48480, 48638, 48951, 49037, 49519, 49528, 49534, 50099, 52734, 53199, 53244, 53548, 53774, 54482, 55130, 55467, 56901, 56902, 56904, 56915, 56920, 56933, 56944, 56972, 57186, 60124, 60169, 60290, 60399, 60403, 60404, 60428, 60484, 60487, 60491, 60502, 60503, 60585, 60586, 60642, 60682, 60686, 60688, 60689, 60695, 60696, 60958, 61705, 62711, 62712, 63190, 63368, 64002, 65897, 67843, 68197, 68379, 70097, 70500, 70595, 70873, 70891, 71150, 71217, 72198, 72260, 73025, 73039, 73195, 74019, 74439, 75334, 75340, 75343, 75344, 75358, 75797, 76166, 77246, 77247, 77250, 77260, 77276, 77278, 77285, 77286, 77294, 77296, 77407, 77498, 77523, 78542, 78633, 78799, 80023, 80113, 80923, 80927, 80938, 80939, 81403, 81507, 83414, 83646, 84005, 84045, 84081, 84096, 85083, 85117, 85118, 85119, 85120, 85121, 85122, 85127, 85128, 85130, 85131, 85132, 85135, 85137, 85138, 85139, 85140, 85141, 85142, 85143, 85145, 85147, 85172, 85173, 85178, 85190, 85191, 85192, 85193, 85194, 85209, 85238, 85243, 85293, 85294, 85295, 85298, 85388, 85392, 85396, 85658, 85755, 85756, 85757, 86315, 86409, 87151, 88013, 89002, 89034, 89037, 89044, 89054, 89067, 89077, 89085, 89087, 89105, 89140, 89157, 89161, 89162, 89165, 89166, 89169, 89178, 89179, 89183, 89441, 89508, 89519, 89555, 90090, 90189, 90895, 90899, 91008, 91199, 92010, 92011, 92081, 92247, 92248, 92331, 92344, 92395, 92609, 92617, 92637, 92725, 92809, 93290, 93314, 93475, 93619, 93636, 93723, 93730, 94013, 94158, 94199, 94505, 94622, 95467, 95757, 95811, 97086, 97089, 97317, 97471, 98077, 98087, 98089, 98127, 98139, 98141, 98165, 98170, 98175, 98194, 98213, 98391, 98417, 98419, 98490, 98496, 98511, 99354, 99529, 99530, 99545, 99629, 99731, 99812`
