### ISSUE TITLE
DAWG is not maintained anymore

### ISSUE THREAD

**Issue by tsx** [closeio/tz-trout#15]
https://github.com/pytries/DAWG seems abandoned 3 years ago. It fails to install on python 3.7. Perhaps we should get rid of it?

**Comment by wojcikstefan** [comment]
The simplest way to get rid of it would be to use regular dicts for the zipcode-to-TZ-ids mapping. I think that's what we did in the past and then added the DAWG as way to reduce the memory footprint. However, there should be a much simpler way around it.

There are ~42k zipcodes in the US and each of them points to a list of TZ ids. That obviously adds up *if you're using a unique list per zip code*. However, most of these values are NOT unique and hence we can probably just make sure that we're reusing the same *instance* of a TZ ID list for each neighboring ZIP code.

**Comment by tsx** [comment]
Got rid of it in #16
